In [1]:
import pandas as pd
pd.set_option('display.max_columns', None) 
pd.set_option('display.max_rows', None)

In [2]:
raw_df = pd.read_csv("../data/train2-25.csv")

In [3]:
print(raw_df.head(10))

        RedFighter        BlueFighter  RedOdds  BlueOdds  RedExpectedValue  \
0  Colby Covington    Joaquin Buckley      205      -250          205.0000
1      Cub Swanson  Billy Quarantillo      124      -148          124.0000
2       Manel Kape        Bruno Silva     -395       310           25.3165
3    Vitor Petrino      Dustin Jacoby     -340       270           29.4118
4     Adrian Yanez      Daniel Marcos      185      -225          185.0000
5  Navajo Stirling        Tuco Tokkos     -750       525           13.3333
6  Michael Johnson     Ottman Azaitar     -230       190           43.4783
7     Joel Alvarez      Drakkar Klose     -425       330           23.5294
8     Sean Woodson   Fernando Padilla     -155       130           64.5161
9      Miles Johns        Felipe Lima      210      -258          210.0000

   BlueExpectedValue        Date             Location Country Winner  \
0            40.0000  12/14/2024  Tampa, Florida, USA     USA   Blue
1            67.5676  12/14/2024  Tampa, Florida, USA     USA    Red
2           310.0000  12/14/2024  Tampa, Florida, USA     USA    Red
3           270.0000  12/14/2024  Tampa, Florida, USA     USA   Blue
4            44.4444  12/14/2024  Tampa, Florida, USA     USA   Blue
5           525.0000  12/14/2024  Tampa, Florida, USA     USA    Red
6           190.0000  12/14/2024  Tampa, Florida, USA     USA    Red
7           330.0000  12/14/2024  Tampa, Florida, USA     USA    Red
8           130.0000  12/14/2024  Tampa, Florida, USA     USA    Red
9            38.7597  12/14/2024  Tampa, Florida, USA     USA   Blue

   TitleBout        WeightClass Gender  NumberOfRounds  BlueCurrentLoseStreak  \
0      False       Welterweight   MALE               5                      0
1      False      Featherweight   MALE               3                      1
2      False          Flyweight   MALE               3                      0
3      False  Light Heavyweight   MALE               3                      2
4      False       Bantamweight   MALE               3                      0
5      False  Light Heavyweight   MALE               3                      2
6      False        Lightweight   MALE               3                      2
7      False        Lightweight   MALE               3                      0
8      False      Featherweight   MALE               3                      0
9      False      Featherweight   MALE               3                      0

   BlueCurrentWinStreak  BlueDraws  BlueAvgSigStrLanded  BlueAvgSigStrPct  \
0                     5          0                 4.13              0.36
1                     0          0                 7.36              0.56
2                     4          0                 3.32              0.48
3                     0          1                 5.50              0.47
4                     4          0                 5.94              0.52
5                     0          0                 3.26              0.43
6                     0          0                 5.73              0.51
7                     4          0                 4.37              0.55
8                     1          0                 6.48              0.42
9                     1          0                 3.29              0.52

   BlueAvgSubAtt  BlueAvgTDLanded  BlueAvgTDPct  BlueLongestWinStreak  \
0            0.0             1.96          0.46                     5
1            1.1             1.24          0.23                     4
2            0.2             2.26          0.28                     4
3            0.0             0.36          0.25                     4
4            0.0             0.25          0.50                     4
5            0.0             1.96          1.00                     0
6            0.0             0.00          0.00                     2
7            0.0             1.58          0.26                     4
8            0.8             0.00          0.00                     1
9            1.3             1.33          0.50                     1

   BlueLosses  BlueTotalRoundsFought  BlueTotalTitleBouts  \
0           4                     34                    0
1           4                     28                    0
2           2                     16                    0
3           6                     35                    0
4           0                     13                    0
5           2                      2                    0
6           2                      4                    0
7           2                     29                    0
8           1                      5                    0
9           0                      3                    0

   BlueWinsByDecisionMajority  BlueWinsByDecisionSplit  \
0                           0                        1
1                           0                        0
2                           0                        0
3                           0                        0
4                           0                        1
5                           0                        0
6                           0                        0
7                           0                        1
8                           0                        0
9                           0                        0

   BlueWinsByDecisionUnanimous  BlueWinsByKO  BlueWinsBySubmission  \
0                            2             7                     0
1                            2             4                     1
2                            0             3                     1
3                            4             4                     0
4                            2             1                     0
5                            0             0                     0
6                            0             2                     0
7                            6             2                     0
8                            0             1                     1
9                            0             0                     1

   BlueWinsByTKODoctorStoppage  BlueWins BlueStance  BlueHeightCms  \
0                            0        10   Southpaw         177.80
1                            0         7   Orthodox         177.80
2                            0         4   Orthodox         162.56
3                            0         8   Orthodox         190.50
4                            0         4   Orthodox         170.18
5                            0         0   Orthodox         193.04
6                            0         2     Switch         172.72
7                            0         9   Orthodox         175.26
8                            0         2   Orthodox         185.42
9                            0         1   Orthodox         167.64

   BlueReachCms  BlueWeightLbs  RedCurrentLoseStreak  RedCurrentWinStreak  \
0        193.04            170                     1                    0
1        177.80            145                     1                    0
2        165.10            125                     1                    0
3        193.04            205                     1                    0
4        175.26            135                     0                    1
5        193.04            205                     0                    1
6        180.34            155                     0                    1
7        177.80            155                     0                    2
8        193.04            145                     0                    5
9        172.72            145                     0                    3

   RedDraws  RedAvgSigStrLanded  RedAvgSigStrPct  RedAvgSubAtt  \
0         0                3.88             0.38           0.2
1         0                4.67             0.50           0.4
2         0                4.44             0.53           0.4
3         0                2.82             0.45           0.8
4         0                6.51             0.41           0.0
5         0                7.07             0.68           0.0
6         0                4.27             0.39           0.0
7         0                4.39             0.52           1.2
8         1                5.58             0.46           0.4
9         0                3.28             0.47           0.0

   RedAvgTDLanded  RedAvgTDPct  RedLongestWinStreak  RedLosses  \
0            3.79         0.44                    7          4
1            1.04         0.50                    6         13
2            0.54         0.33                    4          3
3            3.98         0.66                    5          1
4            0.00         0.00                    6          2
5            0.00         0.00                    1          0
6            0.62         0.41                    4         15
7            0.00         0.00                    4          2
8            0.66         0.62                    3          1
9            1.02         0.20                    3          2

   RedTotalRoundsFought  RedTotalTitleBouts  RedWinsByDecisionMajority  \
0                    58                   4                          0
1                    82                   0                          0
2                    17                   0                          0
3                    14                   0                          0
4                    15                   0                          0
5                     2                   0                          0
6                    74                   1                          0
7                    15                   0                          0
8                    24                   0                          0
9                    29                   0                          0

   RedWinsByDecisionSplit  RedWinsByDecisionUnanimous  RedWinsByKO  \
0                       0                           7            3
1                       1                          10            6
2                       0                           2            2
3                       0                           2            2
4                       1                           0            6
5                       0                           0            1
6                       1                           8            5
7                       0                           0            3
8                       2                           3            2
9                       1                           4            2

   RedWinsBySubmission  RedWinsByTKODoctorStoppage  RedWins RedStance  \
0                    2                           0       12  Orthodox
1                    2                           0       19  Orthodox
2                    0                           0        4  Southpaw
3                    1                           0        5  Orthodox
4                    0                           0        7  Orthodox
5                    0                           0        1  Orthodox
6                    0                           0       14  Southpaw
7                    3                           0        6  Orthodox
8                    0                           0        7  Orthodox
9                    0                           0        7  Orthodox

   RedHeightCms  RedReachCms  RedWeightLbs  RedAge  BlueAge  LoseStreakDif  \
0        180.34       182.88           170      36       30             -1
1        172.72       177.80           145      41       36              0
2        165.10       172.72           125      31       34             -1
3        187.96       195.58           205      27       36              1
4        170.18       177.80           135      31       31              0
5        193.04       200.66           205      27       34              2
6        177.80       185.42           155      38       34              2
7        190.50       195.58           155      31       36              0
8        187.96       198.12           145      32       27              0
9        170.18       167.64           145      30       26              0

   WinStreakDif  LongestWinStreakDif  WinDif  LossDif  TotalRoundDif  \
0             5                   -2      -2        0            -24
1             0                   -2     -12       -9            -54
2             4                    0       0       -1             -1
3             0                   -1       3        5             21
4             3                   -2      -3       -2             -2
5            -1                   -1      -1        2              0
6            -1                   -2     -12      -13            -70
7             2                    0       3        0             14
8            -4                   -2      -5        0            -19
9            -2                   -2      -6       -2            -26

   TotalTitleBoutDif  KODif  SubDif  HeightDif  ReachDif  AgeDif  SigStrDif  \
0                 -4      4      -2      -2.54     10.16      -6       0.25
1                  0     -2      -1       5.08      0.00      -5       2.69
2                  0      1       1      -2.54     -7.62       3      -1.12
3                  0      2      -1       2.54     -2.54       9       2.68
4                  0     -5       0       0.00     -2.54       0      -0.57
5                  0     -1       0       0.00     -7.62       7      -3.81
6                 -1     -3       0      -5.08     -5.08      -4       1.46
7                  0     -1      -3     -15.24    -17.78       5      -0.02
8                  0     -1       1      -2.54     -5.08      -5       0.90
9                  0     -2       1      -2.54      5.08      -4       0.01

   AvgSubAttDif  AvgTDDif  EmptyArena  BMatchWCRank  RMatchWCRank  \
0          -0.2     -1.83         NaN           9.0           6.0
1           0.7      0.20         NaN           NaN           NaN
2          -0.2      1.72         NaN          12.0           9.0
3          -0.8     -3.62         NaN           NaN           NaN
4           0.0      0.25         NaN           NaN           NaN
5           0.0      1.96         NaN           NaN           NaN
6           0.0     -0.62         NaN           NaN           NaN
7          -1.2      1.58         NaN           NaN           NaN
8           0.4     -0.66         NaN           NaN           NaN
9           1.3      0.31         NaN           NaN           NaN

   RWFlyweightRank  RWFeatherweightRank  RWStrawweightRank  \
0              NaN                  NaN                NaN
1              NaN                  NaN                NaN
2              NaN                  NaN                NaN
3              NaN                  NaN                NaN
4              NaN                  NaN                NaN
5              NaN                  NaN                NaN
6              NaN                  NaN                NaN
7              NaN                  NaN                NaN
8              NaN                  NaN                NaN
9              NaN                  NaN                NaN

   RWBantamweightRank  RHeavyweightRank  RLightHeavyweightRank  \
0                 NaN               NaN                    NaN
1                 NaN               NaN                    NaN
2                 NaN               NaN                    NaN
3                 NaN               NaN                    NaN
4                 NaN               NaN                    NaN
5                 NaN               NaN                    NaN
6                 NaN               NaN                    NaN
7                 NaN               NaN                    NaN
8                 NaN               NaN                    NaN
9                 NaN               NaN                    NaN

   RMiddleweightRank  RWelterweightRank  RLightweightRank  RFeatherweightRank  \
0                NaN                6.0               NaN                 NaN
1                NaN                NaN               NaN                 NaN
2                NaN                NaN               NaN                 NaN
3                NaN                NaN               NaN                 NaN
4                NaN                NaN               NaN                 NaN
5                NaN                NaN               NaN                 NaN
6                NaN                NaN               NaN                 NaN
7                NaN                NaN               NaN                 NaN
8                NaN                NaN               NaN                 NaN
9                NaN                NaN               NaN                 NaN

   RBantamweightRank  RFlyweightRank  RPFPRank  BWFlyweightRank  \
0                NaN             NaN       NaN              NaN
1                NaN             NaN       NaN              NaN
2                NaN             9.0       NaN              NaN
3                NaN             NaN       NaN              NaN
4                NaN             NaN       NaN              NaN
5                NaN             NaN       NaN              NaN
6                NaN             NaN       NaN              NaN
7                NaN             NaN       NaN              NaN
8                NaN             NaN       NaN              NaN
9                NaN             NaN       NaN              NaN

   BWFeatherweightRank  BWStrawweightRank  BWBantamweightRank  \
0                  NaN                NaN                 NaN
1                  NaN                NaN                 NaN
2                  NaN                NaN                 NaN
3                  NaN                NaN                 NaN
4                  NaN                NaN                 NaN
5                  NaN                NaN                 NaN
6                  NaN                NaN                 NaN
7                  NaN                NaN                 NaN
8                  NaN                NaN                 NaN
9                  NaN                NaN                 NaN

   BHeavyweightRank  BLightHeavyweightRank  BMiddleweightRank  \
0               NaN                    NaN                NaN
1               NaN                    NaN                NaN
2               NaN                    NaN                NaN
3               NaN                    NaN                NaN
4               NaN                    NaN                NaN
5               NaN                    NaN                NaN
6               NaN                    NaN                NaN
7               NaN                    NaN                NaN
8               NaN                    NaN                NaN
9               NaN                    NaN                NaN

   BWelterweightRank  BLightweightRank  BFeatherweightRank  BBantamweightRank  \
0                9.0               NaN                 NaN                NaN
1                NaN               NaN                 NaN                NaN
2                NaN               NaN                 NaN                NaN
3                NaN               NaN                 NaN                NaN
4                NaN               NaN                 NaN                NaN
5                NaN               NaN                 NaN                NaN
6                NaN               NaN                 NaN                NaN
7                NaN               NaN                 NaN                NaN
8                NaN               NaN                 NaN                NaN
9                NaN               NaN                 NaN                NaN

   BFlyweightRank  BPFPRank BetterRank  Finish FinishDetails  FinishRound  \
0             NaN       NaN        Red  KO/TKO           NaN          3.0
1             NaN       NaN    neither  KO/TKO         Punch          3.0
2            12.0       NaN        Red  KO/TKO       Punches          3.0
3             NaN       NaN    neither  KO/TKO         Punch          3.0

In [4]:
colCount = 0
for each in raw_df:
    colCount += 1
    print(str(colCount) + " " + each)

1 RedFighter
2 BlueFighter
3 RedOdds
4 BlueOdds
5 RedExpectedValue
6 BlueExpectedValue
7 Date
8 Location
9 Country
10 Winner
11 TitleBout
12 WeightClass
13 Gender
14 NumberOfRounds
15 BlueCurrentLoseStreak
16 BlueCurrentWinStreak
17 BlueDraws
18 BlueAvgSigStrLanded
19 BlueAvgSigStrPct
20 BlueAvgSubAtt
21 BlueAvgTDLanded
22 BlueAvgTDPct
23 BlueLongestWinStreak
24 BlueLosses
25 BlueTotalRoundsFought
26 BlueTotalTitleBouts
27 BlueWinsByDecisionMajority
28 BlueWinsByDecisionSplit
29 BlueWinsByDecisionUnanimous
30 BlueWinsByKO
31 BlueWinsBySubmission
32 BlueWinsByTKODoctorStoppage
33 BlueWins
34 BlueStance
35 BlueHeightCms
36 BlueReachCms
37 BlueWeightLbs
38 RedCurrentLoseStreak
39 RedCurrentWinStreak
40 RedDraws
41 RedAvgSigStrLanded
42 RedAvgSigStrPct
43 RedAvgSubAtt
44 RedAvgTDLanded
45 RedAvgTDPct
46 RedLongestWinStreak
47 RedLosses
48 RedTotalRoundsFought
49 RedTotalTitleBouts
50 RedWinsByDecisionMajority
51 RedWinsByDecisionSplit
52 RedWinsByDecisionUnanimous
53 RedWinsByKO
54 RedWinsBySubmission
55 RedWinsByTKODoctorStoppage
56 RedWins
57 RedStance
58 RedHeightCms
59 RedReachCms
60 RedWeightLbs
61 RedAge
62 BlueAge
63 LoseStreakDif
64 WinStreakDif
65 LongestWinStreakDif
66 WinDif
67 LossDif
68 TotalRoundDif
69 TotalTitleBoutDif
70 KODif
71 SubDif
72 HeightDif
73 ReachDif
74 AgeDif
75 SigStrDif
76 AvgSubAttDif
77 AvgTDDif
78 EmptyArena
79 BMatchWCRank
80 RMatchWCRank
81 RWFlyweightRank
82 RWFeatherweightRank
83 RWStrawweightRank
84 RWBantamweightRank
85 RHeavyweightRank
86 RLightHeavyweightRank
87 RMiddleweightRank
88 RWelterweightRank
89 RLightweightRank
90 RFeatherweightRank
91 RBantamweightRank
92 RFlyweightRank
93 RPFPRank
94 BWFlyweightRank
95 BWFeatherweightRank
96 BWStrawweightRank
97 BWBantamweightRank
98 BHeavyweightRank
99 BLightHeavyweightRank
100 BMiddleweightRank
101 BWelterweightRank
102 BLightweightRank
103 BFeatherweightRank
104 BBantamweightRank
105 BFlyweightRank
106 BPFPRank
107 BetterRank
108 Finish
109 FinishDetails
110 FinishRound
111 FinishRoundTime
112 TotalFightTimeSecs
113 RedDecOdds
114 BlueDecOdds
115 RSubOdds
116 BSubOdds
117 RKOOdds
118 BKOOdds

In [5]:
useful_columns = ['RedFighter', 'BlueFighter', 'Finish', 'FinishRound', 'RedOdds', 'BlueOdds',
    'Date', 'Winner', 'TitleBout', 'WeightClass', 'Gender', 'NumberOfRounds', 
    'BlueCurrentLoseStreak', 'BlueCurrentWinStreak', 'BlueLongestWinStreak', 'BlueLosses', 'BlueTotalRoundsFought', 'BlueTotalTitleBouts', 
    'BlueWinsByKO', 'BlueWinsBySubmission', 'BlueWins', 'BlueStance', 'BlueHeightCms', 'BlueReachCms', 'BlueAge', 'BMatchWCRank', 
    'RedCurrentLoseStreak', 'RedCurrentWinStreak', 'RedLongestWinStreak', 'RedLosses', 'RedTotalRoundsFought', 'RedTotalTitleBouts', 
    'RedWinsByKO', 'RedWinsBySubmission', 'RedWins', 'RedStance', 'RedHeightCms', 'RedReachCms', 'RedAge', 'RMatchWCRank', 
    'BetterRank']

dfColumns = raw_df[useful_columns]

print(dfColumns.head())

        RedFighter        BlueFighter  Finish  FinishRound  RedOdds  BlueOdds  \
0  Colby Covington    Joaquin Buckley  KO/TKO          3.0      205      -250
1      Cub Swanson  Billy Quarantillo  KO/TKO          3.0      124      -148
2       Manel Kape        Bruno Silva  KO/TKO          3.0     -395       310
3    Vitor Petrino      Dustin Jacoby  KO/TKO          3.0     -340       270
4     Adrian Yanez      Daniel Marcos   S-DEC          3.0      185      -225

         Date Winner  TitleBout        WeightClass Gender  NumberOfRounds  \
0  12/14/2024   Blue      False       Welterweight   MALE               5
1  12/14/2024    Red      False      Featherweight   MALE               3
2  12/14/2024    Red      False          Flyweight   MALE               3
3  12/14/2024   Blue      False  Light Heavyweight   MALE               3
4  12/14/2024   Blue      False       Bantamweight   MALE               3

   BlueCurrentLoseStreak  BlueCurrentWinStreak  BlueLongestWinStreak  \
0                      0                     5                     5
1                      1                     0                     4
2                      0                     4                     4
3                      2                     0                     4
4                      0                     4                     4

   BlueLosses  BlueTotalRoundsFought  BlueTotalTitleBouts  BlueWinsByKO  \
0           4                     34                    0             7
1           4                     28                    0             4
2           2                     16                    0             3
3           6                     35                    0             4
4           0                     13                    0             1

   BlueWinsBySubmission  BlueWins BlueStance  BlueHeightCms  BlueReachCms  \
0                     0        10   Southpaw         177.80        193.04
1                     1         7   Orthodox         177.80        177.80
2                     1         4   Orthodox         162.56        165.10
3                     0         8   Orthodox         190.50        193.04
4                     0         4   Orthodox         170.18        175.26

   BlueAge  BMatchWCRank  RedCurrentLoseStreak  RedCurrentWinStreak  \
0       30           9.0                     1                    0
1       36           NaN                     1                    0
2       34          12.0                     1                    0
3       36           NaN                     1                    0
4       31           NaN                     0                    1

   RedLongestWinStreak  RedLosses  RedTotalRoundsFought  RedTotalTitleBouts  \
0                    7          4                    58                   4
1                    6         13                    82                   0
2                    4          3                    17                   0
3                    5          1                    14                   0
4                    6          2                    15                   0

   RedWinsByKO  RedWinsBySubmission  RedWins RedStance  RedHeightCms  \
0            3                    2       12  Orthodox        180.34
1            6                    2       19  Orthodox        172.72
2            2                    0        4  Southpaw        165.10
3            2                    1        5  Orthodox        187.96
4            6                    0        7  Orthodox        170.18

   RedReachCms  RedAge  RMatchWCRank BetterRank
0       182.88      36           6.0        Red
1       177.80      41           NaN    neither
2       172.72      31           9.0        Red
3       195.58      27           NaN    neither
4       177.80      31           NaN    neither

In [6]:
missing = pd.concat([dfColumns.isnull().sum(), 100 * dfColumns.isnull().mean()], axis=1)
missing.columns=['count', '%']
missing.sort_values(by='count', ascending = False)

                       count          %
BMatchWCRank            5339  81.623605
RMatchWCRank            4760  72.771747
FinishRound              622   9.509249
Finish                   238   3.638587
BlueStance                 3   0.045865
RedTotalRoundsFought       0   0.000000
BlueReachCms               0   0.000000
BlueAge                    0   0.000000
RedCurrentLoseStreak       0   0.000000
RedCurrentWinStreak        0   0.000000
RedLongestWinStreak        0   0.000000
RedLosses                  0   0.000000
RedFighter                 0   0.000000
RedTotalTitleBouts         0   0.000000
BlueHeightCms              0   0.000000
RedWinsBySubmission        0   0.000000
RedWins                    0   0.000000
RedStance                  0   0.000000
RedHeightCms               0   0.000000
RedReachCms                0   0.000000
RedAge                     0   0.000000
RedWinsByKO                0   0.000000
BlueWins                   0   0.000000
BlueFighter                0   0.000000
BlueWinsBySubmission       0   0.000000
RedOdds                    0   0.000000
BlueOdds                   0   0.000000
Date                       0   0.000000
Winner                     0   0.000000
TitleBout                  0   0.000000
WeightClass                0   0.000000
Gender                     0   0.000000
NumberOfRounds             0   0.000000
BlueCurrentLoseStreak      0   0.000000
BlueCurrentWinStreak       0   0.000000
BlueLongestWinStreak       0   0.000000
BlueLosses                 0   0.000000
BlueTotalRoundsFought      0   0.000000
BlueTotalTitleBouts        0   0.000000
BlueWinsByKO               0   0.000000
BetterRank                 0   0.000000

In [7]:
nullCheck = dfColumns[dfColumns['FinishRound'].isna()][['Finish', 'FinishRound', 'Date', 'RedFighter', 'BlueFighter']]
print(nullCheck.head(10))

      Finish  FinishRound       Date       RedFighter            BlueFighter
1820   U-DEC          NaN  5/22/2021         Rob Font         Cody Garbrandt
1821  KO/TKO          NaN  5/22/2021      Yan Xiaonan          Carla Esparza
1822   U-DEC          NaN  5/22/2021      Justin Tafa         Jared Vanderaa
1823   S-DEC          NaN  5/22/2021  Felicia Spencer           Norma Dumont
1824   U-DEC          NaN  5/22/2021    Ricardo Ramos             Bill Algeo
1825   U-DEC          NaN  5/22/2021  Jack Hermansson       Edmen Shahbazyan
1826     SUB          NaN  5/22/2021     Ben Rothwell          Chris Barnett
1827   U-DEC          NaN  5/22/2021      Court McGee          Claudio Silva
1828  KO/TKO          NaN  5/22/2021      Bruno Silva       Victor Rodriguez
1829   U-DEC          NaN  5/22/2021     Josh Culibao  Shayilan Nuerdanbieke

In [8]:
dfColumns.to_csv('../data/df_columns.csv')

In [12]:
dfFilled = pd.read_csv('../data/df_finishes.csv')

In [13]:
missing = pd.concat([dfFilled.isnull().sum(), 100 * dfFilled.isnull().mean()], axis=1)
missing.columns=['count', '%']
missing.sort_values(by='count', ascending = False)

                       count          %
BMatchWCRank            5339  81.623605
RMatchWCRank            4760  72.771747
FinishRound              158   2.415533
Finish                   157   2.400245
BlueStance                 3   0.045865
Unnamed: 0                 0   0.000000
RedTotalRoundsFought       0   0.000000
BlueReachCms               0   0.000000
BlueAge                    0   0.000000
RedCurrentLoseStreak       0   0.000000
RedCurrentWinStreak        0   0.000000
RedLongestWinStreak        0   0.000000
RedLosses                  0   0.000000
RedWinsByKO                0   0.000000
RedTotalTitleBouts         0   0.000000
RedWinsBySubmission        0   0.000000
RedWins                    0   0.000000
RedStance                  0   0.000000
RedHeightCms               0   0.000000
RedReachCms                0   0.000000
RedAge                     0   0.000000
BlueHeightCms              0   0.000000
BlueWins                   0   0.000000
RedFighter                 0   0.000000
Gender                     0   0.000000
BlueFighter                0   0.000000
RedOdds                    0   0.000000
BlueOdds                   0   0.000000
Date                       0   0.000000
Winner                     0   0.000000
TitleBout                  0   0.000000
WeightClass                0   0.000000
NumberOfRounds             0   0.000000
BlueWinsBySubmission       0   0.000000
BlueCurrentLoseStreak      0   0.000000
BlueCurrentWinStreak       0   0.000000
BlueLongestWinStreak       0   0.000000
BlueLosses                 0   0.000000
BlueTotalRoundsFought      0   0.000000
BlueTotalTitleBouts        0   0.000000
BlueWinsByKO               0   0.000000
BetterRank                 0   0.000000

In [14]:
nullCheck = dfFilled[dfFilled['BlueStance'].isna()][['BlueFighter', 'BlueStance']]
print(nullCheck.head(10))

              BlueFighter BlueStance
401   Daria Zhelezniakova        NaN
1830  Juancamilo Ronderos        NaN
1881          Juan Espino        NaN

In [16]:
dfFilled.loc[dfFilled['BlueFighter'] == 'Daria Zhelezniakova', 'BlueStance'] = 'Orthodox'
dfFilled.loc[dfFilled['BlueFighter'] == 'Juancamilo Ronderos', 'BlueStance'] = 'Southpaw'
dfFilled.loc[dfFilled['BlueFighter'] == 'Juan Espino', 'BlueStance'] = 'Orthodox'

nullCheck = dfFilled[dfFilled['BlueStance'].isna()][['BlueFighter', 'BlueStance']]
print(nullCheck.head(10))

Empty DataFrame
Columns: [BlueFighter, BlueStance]
Index: []

In [17]:
missing = pd.concat([dfFilled.isnull().sum(), 100 * dfFilled.isnull().mean()], axis=1)
missing.columns=['count', '%']
missing.sort_values(by='count', ascending = False)

                       count          %
BMatchWCRank            5339  81.623605
RMatchWCRank            4760  72.771747
FinishRound              158   2.415533
Finish                   157   2.400245
Unnamed: 0                 0   0.000000
RedTotalRoundsFought       0   0.000000
BlueReachCms               0   0.000000
BlueAge                    0   0.000000
RedCurrentLoseStreak       0   0.000000
RedCurrentWinStreak        0   0.000000
RedLongestWinStreak        0   0.000000
RedLosses                  0   0.000000
RedWinsByKO                0   0.000000
RedTotalTitleBouts         0   0.000000
BlueStance                 0   0.000000
RedWinsBySubmission        0   0.000000
RedWins                    0   0.000000
RedStance                  0   0.000000
RedHeightCms               0   0.000000
RedReachCms                0   0.000000
RedAge                     0   0.000000
BlueHeightCms              0   0.000000
BlueWins                   0   0.000000
RedFighter                 0   0.000000
Gender                     0   0.000000
BlueFighter                0   0.000000
RedOdds                    0   0.000000
BlueOdds                   0   0.000000
Date                       0   0.000000
Winner                     0   0.000000
TitleBout                  0   0.000000
WeightClass                0   0.000000
NumberOfRounds             0   0.000000
BlueWinsBySubmission       0   0.000000
BlueCurrentLoseStreak      0   0.000000
BlueCurrentWinStreak       0   0.000000
BlueLongestWinStreak       0   0.000000
BlueLosses                 0   0.000000
BlueTotalRoundsFought      0   0.000000
BlueTotalTitleBouts        0   0.000000
BlueWinsByKO               0   0.000000
BetterRank                 0   0.000000

In [18]:
dfFilled['Date'] = pd.to_datetime(dfFilled['Date'], format="%m/%d/%Y")
dfFilled['Date'].dtype

dtype('<M8[ns]')

In [19]:
startDate = '2016-01-01'
dfDates = dfFilled[dfFilled['Date'] >= startDate]

missing = pd.concat([dfDates.isnull().sum(), 100 * dfDates.isnull().mean()], axis=1)
missing.columns=['count', '%']
missing.sort_values(by='count', ascending = False)

                       count          %
BMatchWCRank            3426  78.416114
RMatchWCRank            2997  68.596933
FinishRound               60   1.373312
Finish                    59   1.350423
Unnamed: 0                 0   0.000000
RedTotalRoundsFought       0   0.000000
BlueReachCms               0   0.000000
BlueAge                    0   0.000000
RedCurrentLoseStreak       0   0.000000
RedCurrentWinStreak        0   0.000000
RedLongestWinStreak        0   0.000000
RedLosses                  0   0.000000
RedWinsByKO                0   0.000000
RedTotalTitleBouts         0   0.000000
BlueStance                 0   0.000000
RedWinsBySubmission        0   0.000000
RedWins                    0   0.000000
RedStance                  0   0.000000
RedHeightCms               0   0.000000
RedReachCms                0   0.000000
RedAge                     0   0.000000
BlueHeightCms              0   0.000000
BlueWins                   0   0.000000
RedFighter                 0   0.000000
Gender                     0   0.000000
BlueFighter                0   0.000000
RedOdds                    0   0.000000
BlueOdds                   0   0.000000
Date                       0   0.000000
Winner                     0   0.000000
TitleBout                  0   0.000000
WeightClass                0   0.000000
NumberOfRounds             0   0.000000
BlueWinsBySubmission       0   0.000000
BlueCurrentLoseStreak      0   0.000000
BlueCurrentWinStreak       0   0.000000
BlueLongestWinStreak       0   0.000000
BlueLosses                 0   0.000000
BlueTotalRoundsFought      0   0.000000
BlueTotalTitleBouts        0   0.000000
BlueWinsByKO               0   0.000000
BetterRank                 0   0.000000

In [21]:
dfDropped = dfDates.dropna(subset=['Finish', 'FinishRound'])
dfDropped = dfDropped.drop('Unnamed: 0', axis=1)

missing = pd.concat([dfDropped.isnull().sum(), 100 * dfDropped.isnull().mean()], axis=1)
missing.columns=['count', '%']
missing.sort_values(by='count', ascending = False)

                       count          %
BMatchWCRank            3370  78.208401
RMatchWCRank            2946  68.368531
RedFighter                 0   0.000000
RedTotalRoundsFought       0   0.000000
BlueReachCms               0   0.000000
BlueAge                    0   0.000000
RedCurrentLoseStreak       0   0.000000
RedCurrentWinStreak        0   0.000000
RedLongestWinStreak        0   0.000000
RedLosses                  0   0.000000
RedTotalTitleBouts         0   0.000000
BlueStance                 0   0.000000
RedWinsByKO                0   0.000000
RedWinsBySubmission        0   0.000000
RedWins                    0   0.000000
RedStance                  0   0.000000
RedHeightCms               0   0.000000
RedReachCms                0   0.000000
RedAge                     0   0.000000
BlueHeightCms              0   0.000000
BlueWins                   0   0.000000
BlueFighter                0   0.000000
BlueWinsBySubmission       0   0.000000
Finish                     0   0.000000
FinishRound                0   0.000000
RedOdds                    0   0.000000
BlueOdds                   0   0.000000
Date                       0   0.000000
Winner                     0   0.000000
TitleBout                  0   0.000000
WeightClass                0   0.000000
Gender                     0   0.000000
NumberOfRounds             0   0.000000
BlueCurrentLoseStreak      0   0.000000
BlueCurrentWinStreak       0   0.000000
BlueLongestWinStreak       0   0.000000
BlueLosses                 0   0.000000
BlueTotalRoundsFought      0   0.000000
BlueTotalTitleBouts        0   0.000000
BlueWinsByKO               0   0.000000
BetterRank                 0   0.000000

In [22]:
df = dfDropped.fillna(16)

missing = pd.concat([df.isnull().sum(), 100 * df.isnull().mean()], axis=1)
missing.columns=['count', '%']
missing.sort_values(by='count', ascending = False)

                       count    %
RedFighter                 0  0.0
BlueStance                 0  0.0
BlueReachCms               0  0.0
BlueAge                    0  0.0
BMatchWCRank               0  0.0
RedCurrentLoseStreak       0  0.0
RedCurrentWinStreak        0  0.0
RedLongestWinStreak        0  0.0
RedLosses                  0  0.0
RedTotalRoundsFought       0  0.0
RedTotalTitleBouts         0  0.0
RedWinsByKO                0  0.0
RedWinsBySubmission        0  0.0
RedWins                    0  0.0
RedStance                  0  0.0
RedHeightCms               0  0.0
RedReachCms                0  0.0
RedAge                     0  0.0
RMatchWCRank               0  0.0
BlueHeightCms              0  0.0
BlueWins                   0  0.0
BlueFighter                0  0.0
BlueWinsBySubmission       0  0.0
Finish                     0  0.0
FinishRound                0  0.0
RedOdds                    0  0.0
BlueOdds                   0  0.0
Date                       0  0.0
Winner                     0  0.0
TitleBout                  0  0.0
WeightClass                0  0.0
Gender                     0  0.0
NumberOfRounds             0  0.0
BlueCurrentLoseStreak      0  0.0
BlueCurrentWinStreak       0  0.0
BlueLongestWinStreak       0  0.0
BlueLosses                 0  0.0
BlueTotalRoundsFought      0  0.0
BlueTotalTitleBouts        0  0.0
BlueWinsByKO               0  0.0
BetterRank                 0  0.0